//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMO.EnPI.AddIn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnPIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnPIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMO.EnPI.AddIn.EnPIResources", typeof(EnPIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Actual Data.
        /// </summary>
        public static string Actual_btntext {
            get {
                return ResourceManager.GetString("Actual_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string ActualTitle {
            get {
                return ResourceManager.GetString("ActualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted R2.
        /// </summary>
        public static string adjR2Title {
            get {
                return ResourceManager.GetString("adjR2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Building Energy Intensity.
        /// </summary>
        public static string adjustedBuildingName {
            get {
                return ResourceManager.GetString("adjustedBuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Data.
        /// </summary>
        public static string adjustedDataName {
            get {
                return ResourceManager.GetString("adjustedDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table below shows the energy and independent variable data originally entered in the tool, the adjusted data, adjustment method, and totals. The data used for the model year is highlighted in green. 
        ///
        ///If a new model is selected for an individual energy source, the adjusted values below will be updated. The EnPI/SEnPI results pages are also linked to this page. Therefore, if changes are made to the adjusted data in the columns below, the results shown in the EnPI and SEnPI pages will update. However, t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string adjustedDataText {
            get {
                return ResourceManager.GetString("adjustedDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original and Modeled Values.
        /// </summary>
        public static string adjustedDataTitle {
            get {
                return ResourceManager.GetString("adjustedDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Production Energy Intensity.
        /// </summary>
        public static string adjustedEnergyIntensName {
            get {
                return ResourceManager.GetString("adjustedEnergyIntensName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP CUSUM.
        /// </summary>
        public static string adjustedModelCUSUMColName {
            get {
                return ResourceManager.GetString("adjustedModelCUSUMColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backcast.
        /// </summary>
        public static string adjustmentBackcast {
            get {
                return ResourceManager.GetString("adjustmentBackcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaining.
        /// </summary>
        public static string adjustmentChaining {
            get {
                return ResourceManager.GetString("adjustmentChaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string adjustmentForecast {
            get {
                return ResourceManager.GetString("adjustmentForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Method.
        /// </summary>
        public static string AdjustmentMethodColName {
            get {
                return ResourceManager.GetString("AdjustmentMethodColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Model.
        /// </summary>
        public static string AdjustmentMethodSEPColName {
            get {
                return ResourceManager.GetString("AdjustmentMethodSEPColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string adjustmentModel {
            get {
                return ResourceManager.GetString("adjustmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted year.
        /// </summary>
        public static string adjyeartableTitle {
            get {
                return ResourceManager.GetString("adjyeartableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Improvement in Energy Intensity (%).
        /// </summary>
        public static string annualImprovementColName {
            get {
                return ResourceManager.GetString("annualImprovementColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Improvement (%).
        /// </summary>
        public static string annualImprovementSEnPIColName {
            get {
                return ResourceManager.GetString("annualImprovementSEnPIColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Savings.
        /// </summary>
        public static string annualSavingsColName {
            get {
                return ResourceManager.GetString("annualSavingsColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP Annual.
        /// </summary>
        public static string annualSEPColName {
            get {
                return ResourceManager.GetString("annualSEPColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backcast.
        /// </summary>
        public static string Backcast_btntext {
            get {
                return ResourceManager.GetString("Backcast_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Year.
        /// </summary>
        public static string BaselineYearColName {
            get {
                return ResourceManager.GetString("BaselineYearColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base year.
        /// </summary>
        public static string baseyeartableTitle {
            get {
                return ResourceManager.GetString("baseyeartableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula for .
        /// </summary>
        public static string bestFormulaLabel {
            get {
                return ResourceManager.GetString("bestFormulaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best model for the data provided is #.
        /// </summary>
        public static string bestModel {
            get {
                return ResourceManager.GetString("bestModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string bestModelStyle {
            get {
                return ResourceManager.GetString("bestModelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Energy Intensity (MMBtu/sq.ft.).
        /// </summary>
        public static string buildingEnPIColName {
            get {
                return ResourceManager.GetString("buildingEnPIColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaining.
        /// </summary>
        public static string Chaining_btntext {
            get {
                return ResourceManager.GetString("Chaining_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 Emission Factor (kg.CO2 eq./MMbtu):.
        /// </summary>
        public static string co2LblEmissionFactor {
            get {
                return ResourceManager.GetString("co2LblEmissionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Source:.
        /// </summary>
        public static string co2LblEnergySource {
            get {
                return ResourceManager.GetString("co2LblEnergySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type/Region:.
        /// </summary>
        public static string co2LblFuelType {
            get {
                return ResourceManager.GetString("co2LblFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (kg.CO2 eq./MMbtu).
        /// </summary>
        public static string co2LblUnits {
            get {
                return ResourceManager.GetString("co2LblUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients and Intercept.
        /// </summary>
        public static string coefficientsTitle {
            get {
                return ResourceManager.GetString("coefficientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string dateColName {
            get {
                return ResourceManager.GetString("dateColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-yyyy.
        /// </summary>
        public static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string dateRangeTitle {
            get {
                return ResourceManager.GetString("dateRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtadjR2 {
            get {
                return ResourceManager.GetString("dtadjR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtAIC {
            get {
                return ResourceManager.GetString("dtAIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String.
        /// </summary>
        public static string dtCaption {
            get {
                return ResourceManager.GetString("dtCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String.
        /// </summary>
        public static string dtFormula {
            get {
                return ResourceManager.GetString("dtFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtIntercept {
            get {
                return ResourceManager.GetString("dtIntercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double[].
        /// </summary>
        public static string dtIVCoefficients {
            get {
                return ResourceManager.GetString("dtIVCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String[].
        /// </summary>
        public static string dtIVNames {
            get {
                return ResourceManager.GetString("dtIVNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double[].
        /// </summary>
        public static string dtIVpVals {
            get {
                return ResourceManager.GetString("dtIVpVals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double[].
        /// </summary>
        public static string dtIVses {
            get {
                return ResourceManager.GetString("dtIVses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int32.
        /// </summary>
        public static string dtModelNo {
            get {
                return ResourceManager.GetString("dtModelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Boolean.
        /// </summary>
        public static string dtModelValid {
            get {
                return ResourceManager.GetString("dtModelValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtpVal {
            get {
                return ResourceManager.GetString("dtpVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtR2 {
            get {
                return ResourceManager.GetString("dtR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtResidual {
            get {
                return ResourceManager.GetString("dtResidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        public static string dtRMSError {
            get {
                return ResourceManager.GetString("dtRMSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnPI Actual Results.
        /// </summary>
        public static string enpiActualTitle {
            get {
                return ResourceManager.GetString("enpiActualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table below shows the unadjusted and adjusted energy consumption and intensity data. The models used to adjust the data for each energy source are shown below the plots and on the individual sheets for each energy source. Note that the tool selects the model that is appropriate for the SEP Program and has the highest adjusted R-squared value..
        /// </summary>
        public static string enpiSheetText {
            get {
                return ResourceManager.GetString("enpiSheetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Energy Performance Results.
        /// </summary>
        public static string enpiSheetTitle {
            get {
                return ResourceManager.GetString("enpiSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnPI Results.
        /// </summary>
        public static string enpiTitle {
            get {
                return ResourceManager.GetString("enpiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Forecast.
        /// </summary>
        public static string Forecast_btntext {
            get {
                return ResourceManager.GetString("Forecast_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model formula.
        /// </summary>
        public static string formulaTitle {
            get {
                return ResourceManager.GetString("formulaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Sq. Ft..
        /// </summary>
        public static string ivBuildingSqFt {
            get {
                return ResourceManager.GetString("ivBuildingSqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Sq. Ft..
        /// </summary>
        public static string ivBuildingSqFt_btntext {
            get {
                return ResourceManager.GetString("ivBuildingSqFt_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDD.
        /// </summary>
        public static string ivCDD {
            get {
                return ResourceManager.GetString("ivCDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDD.
        /// </summary>
        public static string ivCDD_btntext {
            get {
                return ResourceManager.GetString("ivCDD_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        public static string ivHDD {
            get {
                return ResourceManager.GetString("ivHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        public static string ivHDD_btntext {
            get {
                return ResourceManager.GetString("ivHDD_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string ivHumidity {
            get {
                return ResourceManager.GetString("ivHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string ivHumidity_btntext {
            get {
                return ResourceManager.GetString("ivHumidity_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ivOtherVariable {
            get {
                return ResourceManager.GetString("ivOtherVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ivOtherVariable_btntext {
            get {
                return ResourceManager.GetString("ivOtherVariable_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string ivProduction {
            get {
                return ResourceManager.GetString("ivProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string ivProduction_btntext {
            get {
                return ResourceManager.GetString("ivProduction_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string ivTemperature {
            get {
                return ResourceManager.GetString("ivTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string ivTemperature_btntext {
            get {
                return ResourceManager.GetString("ivTemperature_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted R2.
        /// </summary>
        public static string labeladjR2 {
            get {
                return ResourceManager.GetString("labeladjR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC.
        /// </summary>
        public static string labelAIC {
            get {
                return ResourceManager.GetString("labelAIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string labelFormula {
            get {
                return ResourceManager.GetString("labelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients.
        /// </summary>
        public static string labelIVCoefficients {
            get {
                return ResourceManager.GetString("labelIVCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string labelIVNames {
            get {
                return ResourceManager.GetString("labelIVNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable p-Values.
        /// </summary>
        public static string labelIVpVals {
            get {
                return ResourceManager.GetString("labelIVpVals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP Validation Check.
        /// </summary>
        public static string labelIVSEPValChk {
            get {
                return ResourceManager.GetString("labelIVSEPValChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Std. Error.
        /// </summary>
        public static string labelIVses {
            get {
                return ResourceManager.GetString("labelIVses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        public static string labelModelNo {
            get {
                return ResourceManager.GetString("labelModelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is Appropriate for SEP.
        /// </summary>
        public static string labelModelValid {
            get {
                return ResourceManager.GetString("labelModelValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model p-Value.
        /// </summary>
        public static string labelpVal {
            get {
                return ResourceManager.GetString("labelpVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2.
        /// </summary>
        public static string labelR2 {
            get {
                return ResourceManager.GetString("labelR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual.
        /// </summary>
        public static string labelResidual {
            get {
                return ResourceManager.GetString("labelResidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMSError.
        /// </summary>
        public static string labelRMSError {
            get {
                return ResourceManager.GetString("labelRMSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LastYearColName {
            get {
                return ResourceManager.GetString("LastYearColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Energy Source.
        /// </summary>
        public static string lbl_AddEnergySources {
            get {
                return ResourceManager.GetString("lbl_AddEnergySources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Variable.
        /// </summary>
        public static string lbl_AddVariables {
            get {
                return ResourceManager.GetString("lbl_AddVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;EnPI.
        /// </summary>
        public static string menuTitle {
            get {
                return ResourceManager.GetString("menuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of 12 data points needs to be entered for each reporting period. The following year(s) have fewer than 12 data points:.
        /// </summary>
        public static string MinDataPointErr {
            get {
                return ResourceManager.GetString("MinDataPointErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string MinDataPoints {
            get {
                return ResourceManager.GetString("MinDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model #.
        /// </summary>
        public static string modelNumber {
            get {
                return ResourceManager.GetString("modelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model p-Value.
        /// </summary>
        public static string modelPTitle {
            get {
                return ResourceManager.GetString("modelPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string ModelYearColName {
            get {
                return ResourceManager.GetString("ModelYearColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid model could be created from the data provided.
        /// </summary>
        public static string noValidModel {
            get {
                return ResourceManager.GetString("noValidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One valid model was created from the data provided.
        /// </summary>
        public static string oneValidModel {
            get {
                return ResourceManager.GetString("oneValidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnPI.
        /// </summary>
        public static string plotSheetName {
            get {
                return ResourceManager.GetString("plotSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual .
        /// </summary>
        public static string prefixActual {
            get {
                return ResourceManager.GetString("prefixActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeled .
        /// </summary>
        public static string prefixAdjusted {
            get {
                return ResourceManager.GetString("prefixAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Primary .
        /// </summary>
        public static string prefixSEPActual {
            get {
                return ResourceManager.GetString("prefixSEPActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeled Primary .
        /// </summary>
        public static string prefixSEPAdjusted {
            get {
                return ResourceManager.GetString("prefixSEPAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Period Primary .
        /// </summary>
        public static string prefixSEPAnnualSavings {
            get {
                return ResourceManager.GetString("prefixSEPAnnualSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Production.
        /// </summary>
        public static string productionColName {
            get {
                return ResourceManager.GetString("productionColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable p-Values.
        /// </summary>
        public static string pValuesTitle {
            get {
                return ResourceManager.GetString("pValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2.
        /// </summary>
        public static string R2Title {
            get {
                return ResourceManager.GetString("R2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual.
        /// </summary>
        public static string ResidualTitle {
            get {
                return ResourceManager.GetString("ResidualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS Error.
        /// </summary>
        public static string RMSErrorTitle {
            get {
                return ResourceManager.GetString("RMSErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year.
        /// </summary>
        public static string selectYear {
            get {
                return ResourceManager.GetString("selectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose dates for the first year.
        /// </summary>
        public static string selectYear1 {
            get {
                return ResourceManager.GetString("selectYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose dates for the current year.
        /// </summary>
        public static string selectYear2 {
            get {
                return ResourceManager.GetString("selectYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table below shows the unadjusted and adjusted energy consumption. The models used to adjust the data for each energy source are shown under the table below and on the individual sheets for each energy source. Note that the tool selects the model that is appropriate for the SEP Program and has the highest adjusted R-squared value, although evaluating models based on adjusted R-squared is not an SEP requirement.See individual energy source model sheets for adjusted R-squared values..
        /// </summary>
        public static string senpiSheetText {
            get {
                return ResourceManager.GetString("senpiSheetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Energy Performance Results.
        /// </summary>
        public static string senpiSheetTitle {
            get {
                return ResourceManager.GetString("senpiSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP Results.
        /// </summary>
        public static string senpiTitle {
            get {
                return ResourceManager.GetString("senpiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Savings TTM (MMBtu).
        /// </summary>
        public static string sepEnergySavingsTTM {
            get {
                return ResourceManager.GetString("sepEnergySavingsTTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Actual Energy Consumption.
        /// </summary>
        public static string sepTrailingTwelveMonthActualEnergyConsumption {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthActualEnergyConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Actual Energy Consumption to meet 15% improvement target.
        /// </summary>
        public static string sepTrailingTwelveMonthActualEnergyConsumptionFifteenPerTarget {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthActualEnergyConsumptionFifteenPerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Actual Energy Consumption to meet 5% improvement target.
        /// </summary>
        public static string sepTrailingTwelveMonthActualEnergyConsumptionFivePerTarget {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthActualEnergyConsumptionFivePerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Actual Energy Consumption to meet 10% improvement target.
        /// </summary>
        public static string sepTrailingTwelveMonthActualEnergyConsumptionTenPerTarget {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthActualEnergyConsumptionTenPerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Energy Performance Indicator.
        /// </summary>
        public static string sepTrailingTwelveMonthEnergyPerformanceIndicator {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthEnergyPerformanceIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Energy Savings.
        /// </summary>
        public static string sepTrailingTwelveMonthEnergySavings {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthEnergySavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Energy Savings to Meet 15% Improvement.
        /// </summary>
        public static string sepTrailingTwelveMonthEnergySavingsFifteenPerImprovement {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthEnergySavingsFifteenPerImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Energy Savings to Meet 5% Improvement.
        /// </summary>
        public static string sepTrailingTwelveMonthEnergySavingsFivePerImprovement {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthEnergySavingsFivePerImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SEP Only: Trailing Twelve Month Energy Savings to Meet 10% Improvement.
        /// </summary>
        public static string sepTrailingTwelveMonthEnergySavingsTenPerImprovement {
            get {
                return ResourceManager.GetString("sepTrailingTwelveMonthEnergySavingsTenPerImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMBtu.
        /// </summary>
        public static string sourceUnitCheck {
            get {
                return ResourceManager.GetString("sourceUnitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the energy sources selected has not been converted to MMBtu. All energy sources should be converted from site to source and units of MMBtu prior to running regression. Only energy sources in units of MMBtu should be selected in the energy sources box. Would you like to continue without converting from site to source?.
        /// </summary>
        public static string sourceUnitCheckErr {
            get {
                return ResourceManager.GetString("sourceUnitCheckErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        public static string srcCoal {
            get {
                return ResourceManager.GetString("srcCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        public static string srcCoal_btntext {
            get {
                return ResourceManager.GetString("srcCoal_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coke.
        /// </summary>
        public static string srcCoke {
            get {
                return ResourceManager.GetString("srcCoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coke.
        /// </summary>
        public static string srcCoke_btntext {
            get {
                return ResourceManager.GetString("srcCoke_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string srcElectricity {
            get {
                return ResourceManager.GetString("srcElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string srcElectricity_btntext {
            get {
                return ResourceManager.GetString("srcElectricity_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Furnace Gas.
        /// </summary>
        public static string srcFurnaceGas {
            get {
                return ResourceManager.GetString("srcFurnaceGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Furnace Gas.
        /// </summary>
        public static string srcFurnaceGas_btntext {
            get {
                return ResourceManager.GetString("srcFurnaceGas_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual or Heavy Fuel Oil (# 5, 6, Navy Special &amp; Bunker C).
        /// </summary>
        public static string srcHeavyFuelOil {
            get {
                return ResourceManager.GetString("srcHeavyFuelOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual or Heavy Fuel Oil (# 5, 6, Navy Special &amp; Bunker C).
        /// </summary>
        public static string srcHeavyFuelOil_btntext {
            get {
                return ResourceManager.GetString("srcHeavyFuelOil_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distillate or Light Fuel Oil (#1, 2, &amp; 4).
        /// </summary>
        public static string srcLightFuelOil {
            get {
                return ResourceManager.GetString("srcLightFuelOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distillate or Light Fuel Oil (#1, 2, &amp; 4).
        /// </summary>
        public static string srcLightFuelOil_btntext {
            get {
                return ResourceManager.GetString("srcLightFuelOil_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Gas.
        /// </summary>
        public static string srcNaturalGas {
            get {
                return ResourceManager.GetString("srcNaturalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural gas.
        /// </summary>
        public static string srcNaturalGas_btntext {
            get {
                return ResourceManager.GetString("srcNaturalGas_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Energy Source.
        /// </summary>
        public static string srcOtherEnergySource {
            get {
                return ResourceManager.GetString("srcOtherEnergySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Energy Source.
        /// </summary>
        public static string srcOtherEnergySource_btntext {
            get {
                return ResourceManager.GetString("srcOtherEnergySource_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Gas.
        /// </summary>
        public static string srcOtherGas {
            get {
                return ResourceManager.GetString("srcOtherGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Gas.
        /// </summary>
        public static string srcOtherGas_btntext {
            get {
                return ResourceManager.GetString("srcOtherGas_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Liquid.
        /// </summary>
        public static string srcOtherLiquid {
            get {
                return ResourceManager.GetString("srcOtherLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Liquid.
        /// </summary>
        public static string srcOtherLiquid_btntext {
            get {
                return ResourceManager.GetString("srcOtherLiquid_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Solid.
        /// </summary>
        public static string srcOtherSolid {
            get {
                return ResourceManager.GetString("srcOtherSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Solid.
        /// </summary>
        public static string srcOtherSolid_btntext {
            get {
                return ResourceManager.GetString("srcOtherSolid_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Waste.
        /// </summary>
        public static string srcWoodWaste {
            get {
                return ResourceManager.GetString("srcWoodWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Waste.
        /// </summary>
        public static string srcWoodWaste_btntext {
            get {
                return ResourceManager.GetString("srcWoodWaste_btntext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stateData.
        /// </summary>
        public static string stateDataSheetName {
            get {
                return ResourceManager.GetString("stateDataSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawData.
        /// </summary>
        public static string tabNameRollupItem {
            get {
                return ResourceManager.GetString("tabNameRollupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Modeled Energy Consumption (MMBTU).
        /// </summary>
        public static string totalAdjValuesColName {
            get {
                return ResourceManager.GetString("totalAdjValuesColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Modeled Primary Energy Consumption.
        /// </summary>
        public static string totalAdjValuesSEPColName {
            get {
                return ResourceManager.GetString("totalAdjValuesSEPColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Improvement in Energy Intensity (%).
        /// </summary>
        public static string totalImprovementColName {
            get {
                return ResourceManager.GetString("totalImprovementColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Improvement (%).
        /// </summary>
        public static string totalImprovementSEnPIColName {
            get {
                return ResourceManager.GetString("totalImprovementSEnPIColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Performance Improvement.
        /// </summary>
        public static string totalImprovementSEPColName {
            get {
                return ResourceManager.GetString("totalImprovementSEPColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPCumulative.
        /// </summary>
        public static string totalSEPColName {
            get {
                return ResourceManager.GetString("totalSEPColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Source.
        /// </summary>
        public static string totalSourceColName {
            get {
                return ResourceManager.GetString("totalSourceColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Energy Intensity.
        /// </summary>
        public static string unadjustedBuildingColName {
            get {
                return ResourceManager.GetString("unadjustedBuildingColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Data.
        /// </summary>
        public static string unadjustedDataName {
            get {
                return ResourceManager.GetString("unadjustedDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Energy Intensity (MMBtu/unit production).
        /// </summary>
        public static string unadjustedEnergyIntensColName {
            get {
                return ResourceManager.GetString("unadjustedEnergyIntensColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL  Actual Primary Energy (MMBTU).
        /// </summary>
        public static string unadjustedSEPTotalColName {
            get {
                return ResourceManager.GetString("unadjustedSEPTotalColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL  (MMBTU).
        /// </summary>
        public static string unadjustedTotalColName {
            get {
                return ResourceManager.GetString("unadjustedTotalColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is valid.
        /// </summary>
        public static string validModelLabel {
            get {
                return ResourceManager.GetString("validModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent variables.
        /// </summary>
        public static string variablesTitle {
            get {
                return ResourceManager.GetString("variablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cell is blank in the inputs..
        /// </summary>
        public static string warningNullValue {
            get {
                return ResourceManager.GetString("warningNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted values are out of the range of three standard deviations of the model year data. This may indicate an error in the data, or may indicate that a different model year should be used. If a large number of values are out of range, it is recommended that the analysis be redone, using a different model year..
        /// </summary>
        public static string warningOutOfRange {
            get {
                return ResourceManager.GetString("warningOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model was created using less than 10 reference points; this may negatively impact the accuracy of the model..
        /// </summary>
        public static string warningSmallModel {
            get {
                return ResourceManager.GetString("warningSmallModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cell has invalid character(s) in the inputs..
        /// </summary>
        public static string warningSplChars {
            get {
                return ResourceManager.GetString("warningSplChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string warningThreshold {
            get {
                return ResourceManager.GetString("warningThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BBBP Annual Report.
        /// </summary>
        public static string WizardStep10Title {
            get {
                return ResourceManager.GetString("WizardStep10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the EnPI Step-by-step Wizard.
        /// </summary>
        public static string WizardStep1Title {
            get {
                return ResourceManager.GetString("WizardStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Enter your Energy Data and Independent Variables.
        /// </summary>
        public static string WizardStep2Title {
            get {
                return ResourceManager.GetString("WizardStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.1: Enter your Energy Data.
        /// </summary>
        public static string WizardStep3Title {
            get {
                return ResourceManager.GetString("WizardStep3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.2: Enter Independent Variables.
        /// </summary>
        public static string WizardStep4Title {
            get {
                return ResourceManager.GetString("WizardStep4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Assign labels to your reporting periods.
        /// </summary>
        public static string WizardStep5Title {
            get {
                return ResourceManager.GetString("WizardStep5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Select a Calculation Method.
        /// </summary>
        public static string WizardStep6Title {
            get {
                return ResourceManager.GetString("WizardStep6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Energy Data Conversions.
        /// </summary>
        public static string WizardStep7Title {
            get {
                return ResourceManager.GetString("WizardStep7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnPI Results.
        /// </summary>
        public static string WizardStep8Title {
            get {
                return ResourceManager.GetString("WizardStep8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Roll Up.
        /// </summary>
        public static string WizardStep9Title {
            get {
                return ResourceManager.GetString("WizardStep9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon..
        /// </summary>
        public static string WizzardStep10Question1 {
            get {
                return ResourceManager.GetString("WizzardStep10Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep10Question2 {
            get {
                return ResourceManager.GetString("WizzardStep10Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will step you through how to use the tool. The wizard is not needed to run the tool. All commands needed for the tool are located in the top navigation. 
        ///
        ///For additional information on how to use the EnPI tool, please see the EnPI User Manual.
        ///
        ///
        ///.
        /// </summary>
        public static string WizzardStep1Question1 {
            get {
                return ResourceManager.GetString("WizzardStep1Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep1Question2 {
            get {
                return ResourceManager.GetString("WizzardStep1Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your data already in the sheet or do you need to enter your energy streams and independent variables?.
        /// </summary>
        public static string WizzardStep2Question1 {
            get {
                return ResourceManager.GetString("WizzardStep2Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: An independent variable is any variable that affects the energy consumption in the plant. Examples of independent variables include cooling degree days, heating degree days, and production..
        /// </summary>
        public static string WizzardStep2Question2 {
            get {
                return ResourceManager.GetString("WizzardStep2Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting “Add an Energy source”, copy and paste, or manually enter the energy data for the plant. The fuel type and unit must go in the column header..
        /// </summary>
        public static string WizzardStep3Question1 {
            get {
                return ResourceManager.GetString("WizzardStep3Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep3Question2 {
            get {
                return ResourceManager.GetString("WizzardStep3Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting “Add an Independent Variable”, copy and paste, or manually enter the data for the plant..
        /// </summary>
        public static string WizzardStep4Question1 {
            get {
                return ResourceManager.GetString("WizzardStep4Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: An independent variable is any variable that affects the energy consumption in the plant. Examples of independent variables include cooling degree days, heating degree days, and production..
        /// </summary>
        public static string WizzardStep4Question2 {
            get {
                return ResourceManager.GetString("WizzardStep4Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A “Period” column needs to be added to define the reporting periods for each data point and for the tool to calculate the performance indicators. The reporting periods assigned to the data do not need to follow the calendar year. If a company reports along their fiscal year, enter the fiscal year which corresponds to each data point in the “Period” column.
        /// 
        ///The reporting label for each data point in the same reporting year needs to have the same format. For example, if two data points fall within the 200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WizzardStep5Question1 {
            get {
                return ResourceManager.GetString("WizzardStep5Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep5Question2 {
            get {
                return ResourceManager.GetString("WizzardStep5Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to perform regression analysis on your data or use actual data to calculate the performance indicators?.
        /// </summary>
        public static string WizzardStep6Question1 {
            get {
                return ResourceManager.GetString("WizzardStep6Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep6Question2 {
            get {
                return ResourceManager.GetString("WizzardStep6Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your energy data has not been converted to source data and units of MMBtu, please use the “Convert Units” below. Source energy (also known as primary energy) encompasses all the energy used in delivering energy to a site, including power generation and transmission, and distribution losses..
        /// </summary>
        public static string WizzardStep7Question1 {
            get {
                return ResourceManager.GetString("WizzardStep7Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep7Question2 {
            get {
                return ResourceManager.GetString("WizzardStep7Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models for each individual energy source are shown on the sheets with the individual energy sources as labels. The model that meets SEP requirements and has the highest adjusted R-square value will be highlighted in green.
        ///
        ///To switch the models, select “Change Models” below or in the navigation at the top of the tool. Note: you must be on a sheet containing the models in order to switch the models.
        ///..
        /// </summary>
        public static string WizzardStep8Question1 {
            get {
                return ResourceManager.GetString("WizzardStep8Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep8Question2 {
            get {
                return ResourceManager.GetString("WizzardStep8Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EnPI tool can be used to aggregate the data for multiple plants and calculate energy performance indicators at a corporate level. To aggregate data for multiple plants, select “Roll-up” below or from the navigation at the top under EnPI..
        /// </summary>
        public static string WizzardStep9Question1 {
            get {
                return ResourceManager.GetString("WizzardStep9Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizzardStep9Question2 {
            get {
                return ResourceManager.GetString("WizzardStep9Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string yearColName {
            get {
                return ResourceManager.GetString("yearColName", resourceCulture);
            }
        }
    }
}
